# Generated by Django 3.2.25 on 2024-09-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20240930_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='seconds',
        ),
    ]
