# Generated by Django 3.2.25 on 2024-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20240930_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
