# Generated by Django 3.2.25 on 2024-09-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_hours',
            field=models.IntegerField(default=24),
        ),
    ]
