# Generated by Django 3.2.25 on 2024-09-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20240930_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='task',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='seconds',
        ),
    ]
